export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_SEARCH = 'SET_CURRENT_SEARCH';
export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
export const CHECK_ADD_POP_UP = 'CHECK_ADD_POP_UP';